// Copyright (c) 2015-2022 The PIVX Core developers
// Copyright (c) 2024 The CLORE Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef CLORE_STAKEMODIFIER_H
#define CLORE_STAKEMODIFIER_H

#include "chain.h"
#include "primitives/block.h"
#include "uint256.h"

// Stake Modifier (hash modifier of proof-of-stake):
// The purpose of stake modifier is to prevent a txout (coin) owner from
// computing future proof-of-stake generated by this txout at the time
// of transaction confirmation. To meet kernel protocol, the txout
// must hash with a future stake modifier to generate the proof.
// Stake modifier consists of bits each of which is contributed from a
// particular block in a way such that later blocks cannot modify
// earlier blocks' stake modifier bits.
class CStakeModifier
{
private:
    uint64_t nStakeModifier;
    int nStakeModifierHeight;
    int64_t nStakeModifierTime;

public:
    CStakeModifier() : nStakeModifier(0), nStakeModifierHeight(0), nStakeModifierTime(0) {}

    CStakeModifier(uint64_t modifier, int height, int64_t time) : nStakeModifier(modifier), nStakeModifierHeight(height), nStakeModifierTime(time) {}

    uint64_t GetStakeModifier() const { return nStakeModifier; }
    int GetStakeModifierHeight() const { return nStakeModifierHeight; }
    int64_t GetStakeModifierTime() const { return nStakeModifierTime; }
};

// Compute the hash modifier for proof-of-stake
bool ComputeNextStakeModifier(const CBlockIndex* pindexPrev, uint64_t& nStakeModifier, bool& fGeneratedStakeModifier);

// Get the stake modifier specified by the protocol to hash for a stake kernel
bool GetKernelStakeModifier(uint256 hashBlockFrom, uint64_t& nStakeModifier, int& nStakeModifierHeight, int64_t& nStakeModifierTime, bool fPrintProofOfStake = false);

// Get stake modifier checksum
uint256 ComputeStakeModifierCheckpoint(const CBlockIndex* pindex);

// Check stake modifier hard checkpoints
bool CheckStakeModifierCheckpoints(int nHeight, uint64_t nStakeModifierChecksum);

#endif // CLORE_STAKEMODIFIER_H